// This class would contain backend logic for the WeatherApp
// such as fetching weather data from an API, processing it,
// and providing it to the WeatherApp GUI.
import java.net.*;
import java.util.Scanner;
import org.json.simple.*;
import org.json.simple.parser.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;



public class WeatherAppBackend {
    public static JSONObject fetchData(String location){
        JSONArray locationData = getLocationData(location);

        if(locationData == null || locationData.isEmpty()){
            System.out.println("No location data found for: " + location);
            return null;
        }

        // for simplicity, take the first result
        JSONObject firstLocation = (JSONObject) locationData.get(0);
        double latitude = (double) firstLocation.get("latitude");
        double longitude = (double) firstLocation.get("longitude");

        String weatherUrl = "https://api.open-meteo.com/v1/forecast?latitude=" + latitude + "&longitude=" + longitude + "&hourly=temperature_2m,weather_code,wind_speed_10m,relative_humidity_2m";

        try{
            // call the api to get the weather data
            HttpURLConnection conn = fetchApiResponse(weatherUrl);

            // check the connection, here 200 means success
            if(conn.getResponseCode() != 200){
                System.out.println("Error: Could not connect to the API. HTTP code: " + conn.getResponseCode());
                return null;  
            }    

            // if successful, then parse and store the data.
            StringBuilder resultJson = new StringBuilder();
            Scanner scanner = new Scanner(conn.getInputStream());

            // reads through the data generated by the API call.
            while (scanner.hasNextLine()){
                resultJson.append(scanner.nextLine());
            }

            // close the scanner and disconnect the api connection. 
            scanner.close();
            conn.disconnect();

            // parse the JSON data
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(String.valueOf(resultJson));

            JSONObject hourly = (JSONObject) jsonObject.get("hourly");

            // we want to get the current hours data, so we need to get the info of index 0 of the arrays
            JSONArray time = (JSONArray) hourly.get("time");
            int index = findIndexOfCurrentHour(time);


            // get the tempature data
            JSONArray temperatureArray = (JSONArray) hourly.get("temperature_2m");
            double currentTemperature = (double) temperatureArray.get(index);   

            // get the weather code data
            JSONArray weatherCodeArray = (JSONArray) hourly.get("weather_code");   
            String currentWeatherCode = convertWeatherCode((long) weatherCodeArray.get(index));

            // get humidity data
            JSONArray relateiveHumidityArray = (JSONArray) hourly.get("relative_humidity_2m");
            long currentHumidity = (long) relateiveHumidityArray.get(index);

            // get windspeed data
            JSONArray windspeedArray = (JSONArray) hourly.get("wind_speed_10m");
            double currentWindspeed = (double) windspeedArray.get(index);


            // build the results that can be excessed by the GUI
            JSONObject weatherResults = new JSONObject();
            weatherResults.put("temperature", currentTemperature);
            weatherResults.put("weather_condition", currentWeatherCode);
            weatherResults.put("humidity", currentHumidity);
            weatherResults.put("windspeed", currentWindspeed);
            

            return weatherResults;

        }
        catch(Exception e){
            e.printStackTrace();
        }

        
        return firstLocation;
    }

    public static JSONArray getLocationData(String location){
        // logic to fetch location data from weather API
        location = location.replace(" ", "+");

        String urlString = "https://geocoding-api.open-meteo.com/v1/search?name=" + location + "&count=10&language=en&format=json";
    
        try{
            // attempt to make a connection
            HttpURLConnection conn = fetchApiResponse(urlString);

            if (conn == null) {
                System.out.println("Error: Could not establish connection");
                return null;
            }

            // check the http code to check if the connection was successful
            if(conn.getResponseCode() != 200){
                System.out.println("Error: Could not connect to the API. HTTP code: " + conn.getResponseCode());
                return null;
            } else {
                // store the API results
                StringBuilder resultJson = new StringBuilder();
                Scanner scanner = new Scanner(conn.getInputStream());

                // reads and stores the data in your string builder
                while (scanner.hasNextLine()){
                    resultJson.append(scanner.nextLine());
                }

                // close the scanner
                scanner.close();

                // close the connection
                conn.disconnect();

            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(resultJson.toString());

            // stores the results array in JSON format
            JSONArray locationData = (JSONArray) jsonObject.get("results");

            // return the location data
            return locationData;



        }

        } catch (Exception e){
            e.printStackTrace();
            
            return null;
        }



    } 

    // fixed name and implementation
    private static HttpURLConnection fetchApiResponse(String urlString){
        try{
            URL url = URI.create(urlString).toURL();
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();

            conn.setRequestMethod("GET");
            conn.connect();
            return conn;

        }catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }

    public static int findIndexOfCurrentHour(JSONArray timeList){
        // logic to find the index of the current hour in the time array
        // for simplicity, returning 0
        String currentTime = getCurrentTime();

        // iterate through the timeList to find the matching time
        for (int i = 0 ; i < timeList.size() ; i++){
            String timeEntry = (String) timeList.get(i);
            if (timeEntry.equals(currentTime)){
                return i;
            }
        }

        return 0;

    }

    public static String getCurrentTime(){
        LocalDateTime currentDateTime = LocalDateTime.now();

        // format the date and time info we recieve 
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH':00'");

        // format the current date time to match the API format
        String formattedDateTime = currentDateTime.format(formatter);

        return formattedDateTime;
    }

    private static String convertWeatherCode(long code){
        // logic to convert weather code to human-readable format
        switch ((int) code) {
            case 0:
                return "Clear sky";
            case 1:
            case 2:
            case 3:
                return "Partly cloudy";
            case 45:
            case 48:
                return "Fog";
            case 51:
            case 53:
            case 55:
                return "Drizzle";
            case 61:
            case 63:
            case 65:
                return "Rain";
            case 71:
            case 73:
            case 75:
                return "Snow";
            case 80:
            case 81:
            case 82:
                return "Rain showers";
            case 95:
                return "Thunderstorm";
            case 96:
            case 99:
                return "Thunderstorm with hail";
            
            default:
                return "Unknown";
        }
    }

}